<?php

namespace App\DataFixtures;

use App\Entity\Generique;
use App\Entity\Album;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Member;

class AppFixtures extends Fixture
{
    // defines reference names for instances of Rack
    private const ALBUM_THOMAS_1 = 'thomas-album-1';
    private const ALBUM_MAXIME_1 = 'maxime-album-1';
    private const ALBUM_MAXIME_2 = 'maxime-album-2';

    private const THOMAS = 'thomas';
    private const MAXIME = 'maxime';
    /**
     * Generates initialization data for album : [description]
     * @return \\Generator
     */
    
    private static function memberDataGenerator()
    {
        yield ["Schneider", "Thomas", null, self::THOMAS];
        yield ["Sansané", "Maxime", "CrafteurMax", self::MAXIME];
    }
    
    private static function albumDataGenerator()
    {
        yield [self::THOMAS, "Album de génériques de Thomas", self::ALBUM_THOMAS_1];
        yield [self::MAXIME, "Les génériques de Maxime", self::ALBUM_MAXIME_1];
        yield [self::MAXIME, "Les autres génériques de Maxime", self::ALBUM_MAXIME_2];
    }

    /**
     * Generates initialization data for generique recommendations:
     *  [film_title, film_year, recommendation]
     * @return \\Generator
     */
    private static function generiqueGenerator()
    {
        yield [self::ALBUM_THOMAS_1, "Oshi no Ko", "OP", 1,"Idol", "Yoasobi"];
        yield [self::ALBUM_THOMAS_1, "Da Wang Rao Ming", "OP", 1 , "C'est chinois", "Jsp"];
        yield [self::ALBUM_MAXIME_1, "Assassination Classroom", "ED", 4 , "Bye bye Yesterday", "3-nen E-gatsu"];
        yield [self::ALBUM_MAXIME_2, "Sword Art Oneline", "OP" , 3, "Ignite", "Lisa (non)"];
    }
    

    public function load(ObjectManager $manager)
    {
        $inventoryRepo = $manager->getRepository(Album::class);

        foreach (self::memberDataGenerator() as [$nom, $prenom, $pseudo, $memberReference] ) {
            $member = new Member();
            $member->setNom($nom);
            $member->setPrenom($prenom);
            $member->setPseudo($pseudo);
            $manager->persist($member);
            $manager->flush();
            
            $this->addReference($memberReference, $member);
        }
        
        foreach (self::albumDataGenerator() as [$memberReference, $description, $albumReference] )
        {
            $album = new Album();
            $album->setDescription($description);
            $member = $this->getReference($memberReference);
            $member->addAlbum($album);
            $manager->persist($album);
            $manager->flush();
            
            // Once the Album instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($albumReference, $album);
        }   
        
        foreach (self::generiqueGenerator() as [$albumReference, $anime, $type , $numero, $titre, $artiste] )
        {
            $generique = new Generique();
            $generique->setAnime($anime);
            $generique->setType($type);
            $generique->setNumero($numero);
            $generique->setTitre($titre);
            $generique->setArtiste($artiste);        
            
            // Retrieve the One-side instance of Album from its reference name
            $album = $this->getReference($albumReference);
            // Add the Many-side Guitar to its containing rack
            $album->addGenerique($generique);

            // Requir that the ORM\OneToMany attribute on Rack::guitars has "cascade: ['persist']"
            $manager->persist($generique);
        }
        $manager->flush();
    }
}
