<?php

namespace App\DataFixtures;

use App\Entity\Generique;
use App\Entity\Album;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use App\Entity\Member;

class AppFixtures extends Fixture
{
    // defines reference names for instances of Rack
    private const ALBUM_THOMAS = 'thomas-album';
    private const ALBUM_MAXIME = 'maxime-album';

    private const THOMAS = 'thomas';
    private const MAXIME = 'maxime';
    /**
     * Generates initialization data for album : [nom]
     * @return \\Generator
     */
    
    private static function memberDataGenerator()
    {
        yield ["Schneider", "Thomas", null, self::THOMAS];
        yield ["Sansané", "Maxime", "CrafteurMax", self::MAXIME];
    }
    
    private static function albumDataGenerator()
    {
        yield [self::THOMAS, "Album de génériques de Thomas", self::ALBUM_THOMAS];
        yield [self::MAXIME, "Les génériques de Maxime", self::ALBUM_MAXIME];
    }

    /**
     * Generates initialization data for generique recommendations:
     *  [film_title, film_year, recommendation]
     * @return \\Generator
     */
    private static function generiqueGenerator()
    {
        yield [self::ALBUM_THOMAS, "Oshi no Ko", "OP", 1,"Idol", "Yoasobi"];
        yield [self::ALBUM_THOMAS, "Link Click", "ED", 1 , "Overthink", "Fan-Ka"];
        yield [self::ALBUM_THOMAS, "Time Shadows", "OP", 2 , "Natsuyume Noisy", "Asaka"];        
        yield [self::ALBUM_MAXIME, "Assassination Classroom", "OP", 4 , "Bye bye Yesterday", "3-nen E-gumi Utatan"];
        yield [self::ALBUM_MAXIME, "Vinland Saga", "ED" , 3, "Without Love", "LMYK"];
    }
    

    public function load(ObjectManager $manager)
    {
        $inventoryRepo = $manager->getRepository(Album::class);

        foreach (self::memberDataGenerator() as [$nom, $prenom, $pseudo, $memberReference] ) {
            $member = new Member();
            $member->setNom($nom);
            $member->setPrenom($prenom);
            $member->setPseudo($pseudo);
            $manager->persist($member);
            $manager->flush();
            
            $this->addReference($memberReference, $member);
        }
        
        foreach (self::albumDataGenerator() as [$memberReference, $nom, $albumReference] )
        {
            $album = new Album();
            $album->setNom($nom);
            $member = $this->getReference($memberReference);
            $manager->persist($album);
            $manager->flush();
            
            $album->setMember($member);
            
            // Once the Album instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($albumReference, $album);
        }   
        
        foreach (self::generiqueGenerator() as [$albumReference, $anime, $type , $numero, $titre, $artiste] )
        {
            $generique = new Generique();
            $generique->setAnime($anime);
            $generique->setType($type);
            $generique->setNumero($numero);
            $generique->setTitre($titre);
            $generique->setArtiste($artiste);        
            
            // Retrieve the One-side instance of Album from its reference name
            $album = $this->getReference($albumReference);
            // Add the Many-side Guitar to its containing rack
            $album->addGenerique($generique);

            // Requir that the ORM\OneToMany attribute on Rack::guitars has "cascade: ['persist']"
            $manager->persist($generique);
        }
        $manager->flush();
    }
}
